version: '3.9'

services:
  postgres:
    image: postgres:14
    container_name: travel-steps
    restart: always
    environment:
      - POSTGRES_USER=${DB_USERNAME_DEV}
      - POSTGRES_PASSWORD=${DB_PASSWORD_DEV}
      - POSTGRES_DB=${DB_NAME_DEV}
    ports:
      - "${DB_PORT_DEV}:5432"